# This is a clean image containing ffmpeg already built for an alpine base

FROM         jrottenberg/ffmpeg


RUN apt-get update
RUN apt-get install -y software-properties-common vim
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv


# update pip
RUN python3.6 -m pip install pip --upgrade
RUN python3.6 -m pip install wheel

RUN python3.6 -m pip install azure-storage-blob==1.5.0
RUN python3.6 -m pip install numpy==1.14.6

WORKDIR /app
ADD . /app

# RUN pip install -r requirements.txt